name: raaz
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  flutter_media_metadata: ^1.0.0+1

  # --- Isar Database Dependencies ---
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # Needed for Isar bindings
  path: ^1.9.0 # Often used with path_provider and databases
  just_audio: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # --- Isar Code Generation Dependencies ---
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9 # Or latest compatible version

flutter:
  uses-material-design: true